ICU 3488: Display DNS Names for AWS Hosts in Admin UI
hashicorp/boundary-ui pull request #1001
Opened 2022-02-24 21:53 UTC by cameronperera

The test cases need to be updated to handle the different type of host-catalogs properly. Test will be updated and added in a later PR.

2022-02-24 21:53 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/boundary-ui?pullRequest=1001)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/boundary-ui?pullRequest=1001)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**Cameron Perera** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/boundary-ui?pullRequest=1001).</sub>

2022-02-25 16:13 UTC, calcaide approved these changes
LGTM!! Congrats on your first PR as member of Boundary team :)

2022-02-25 16:48 UTC, randallmorey requested changes

2022-02-25 16:48 UTC, randallmorey commented on addons/core/translations/en-us.yaml
> +  dns-names: DNS Names
`dns_names` is a field, so we could move this translation into `core/translations/form/` and treat is a a label.  Similarly, `ip_addresses` is also a form field and could be moved (as a separate PR).

2022-02-25 19:25 UTC, cameronperera commented
Closing PR due to CLA issues. Opened this [PR](https://github.com/hashicorp/boundary-ui/pull/1004) that resolves CLA signing issues.

2022-02-25 19:25 UTC, closed without merging