feat: 🎸 Add "worker_filter" attribute to target model
hashicorp/boundary-ui pull request #1049
Opened 2022-04-08 21:19 UTC by cameronperera

✅ Closes: ICU-3887

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-3887)

## Description

Add `worker_filter` attribute to target model and matching tests

2022-04-11 13:07 UTC, randallmorey requested changes

2022-04-11 15:15 UTC, cameronperera commented on addons/api/addon/generated/models/target.js
> +  @attr('string', {
Swagger description added.

2022-04-11 18:30 UTC, DhariniJeeva commented
Awesome work! LGTM!

2022-04-11 18:30 UTC, DhariniJeeva approved these changes

2022-04-12 15:16 UTC, calcaide approved these changes
LGTM! Nice work :ok_hand:

2022-04-12 21:16 UTC, merged