feat: 🎸 Update Target types help text
hashicorp/boundary-ui pull request #1064
Opened 2022-04-20 17:19 UTC by cameronperera

✅ Closes: ICU-4014

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-4014)

## Description

Update Radio card help text for TCP and SSH targets. Please let me know if there is a better solution to the text spacing issue seen in the screenshots below.

:technologist: [Admin preview](PATH_TO_FEATURE)

### Screenshots (if appropriate):
Below is the new changes. Radio card has been changed to a `tile` layout to make room for TCP help text.
New Target screen:
<img width="656" alt="Screen Shot 2022-04-20 at 11 56 51 AM" src="https://user-images.githubusercontent.com/29386339/164286221-29e84d78-7f4b-43db-81fa-e98514b4f3a6.png">
View/Edit Target screen:
<img width="656" alt="Screen Shot 2022-04-20 at 11 57 02 AM" src="https://user-images.githubusercontent.com/29386339/164286222-d0935e4e-5303-4864-9c38-5da161677308.png">

Below has the new text changes but keeps the current `wide` layout for the radio card. You can see that the TCP help text is cut off.
New Target screen:
<img width="656" alt="Screen Shot 2022-04-20 at 11 57 36 AM" src="https://user-images.githubusercontent.com/29386339/164286225-6c41b7c2-7573-4b43-ad8f-a40e4c13d84a.png">
View/Edit Target screen:
<img width="656" alt="Screen Shot 2022-04-20 at 11 57 28 AM" src="https://user-images.githubusercontent.com/29386339/164286223-6462f494-369d-4d39-8c41-e0b51b8845a1.png">

2022-04-20 17:34 UTC, randallmorey requested changes
Looking good!  Can we add a little padding on the bottom of the card between the text and button to match the top padding?  It feels a bit tight.  Might also try matching the distance from the top fo the card to the start of the paragraph.

2022-04-20 19:16 UTC, randallmorey requested changes
Question, why is the label/title centered?

2022-04-20 20:01 UTC, cameronperera commented
> Question, why is the label/title centered?

Tile layout makes it centered. Which I am not a huge fan of so I am going to change it back to wide and see if I can adjust the styles accordingly to resolve the text cutoff issue.

2022-04-21 16:56 UTC, calcaide approved these changes
Latest changes mentioned on Slack thread so all good! Awesome job!

2022-04-21 18:00 UTC, ZedLi approved these changes
I like the way it looks too, the spacing helps, good job!

2022-04-21 18:16 UTC, DhariniJeeva approved these changes

2022-04-21 18:51 UTC, merged