chore: move onboarding to top level
hashicorp/boundary-ui pull request #1131
Opened 2022-06-10 12:52 UTC by randallmorey

## Description

This PR moves onboarding to the top level to avoid revealing the sidebar.

2022-06-10 21:12 UTC, cameronperera approved these changes
LGTM! Thanks for re...routing the onboarding work.

2022-06-10 21:19 UTC, cameronperera requested changes

2022-06-10 21:19 UTC, cameronperera commented on ui/admin/app/routes/onboarding.js
> +    if (orgs.length) this.router.transitionTo('index');
We are getting a lint error here. Should `orgs` be `model`?
```suggestion
  redirect(model) {
    // If there are orgs already created, redirect to index.
    if (model.length) this.router.transitionTo('index');
```

2022-06-10 21:44 UTC, cameronperera approved these changes
LGTM!

2022-06-13 16:21 UTC, DhariniJeeva approved these changes

2022-06-13 20:38 UTC, merged