create static credential store form and route updates
hashicorp/boundary-ui pull request #1195
Opened 2022-07-15 23:09 UTC by DhariniJeeva

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5172)

## Description

This pr splits the existing credential store form into static and vault types and updates the route to support the type change.

TODO: test this create flow against boundary instance

:technologist: [Admin preview](PATH_TO_FEATURE)

:rose: [Rose preview](PATH_TO_FEATURE)

:desktop_computer: [Desktop preview](PATH_TO_FEATURE)

### Screenshots (if appropriate):

2022-07-18 21:34 UTC, cameronperera requested changes

2022-07-18 21:34 UTC, cameronperera commented on ui/admin/app/components/form/credential-store/vault/index.hbs
> +    />
Can this code be updated to use the radio card? That should be fine to display even if static credential work is not enabled yet.

2022-07-19 14:24 UTC, cameronperera approved these changes
LGTM!

2022-07-19 15:16 UTC, calcaide approved these changes
LGTM!

2022-07-19 16:29 UTC, merged