test: 💍 credential store CRUDL tests
hashicorp/boundary-ui pull request #1212
Opened 2022-07-22 23:27 UTC by lisbet-alvarez

✅ Closes: ICU-5329

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-5329)

## Description
Acceptance tests revised to test both static and vault types of credential stores.

2022-07-25 17:26 UTC, cameronperera requested changes
Overall looks good. In the update-test we have test for the static Credential Stores but not for Vault types. We should add those in as well.

2022-07-25 17:26 UTC, cameronperera commented on ui/admin/tests/acceptance/credential-store/update-test.js
>    });
Do we need a matching test for Vault Credential stores here?

2022-07-25 19:43 UTC, lisbet-alvarez commented on ui/admin/tests/acceptance/credential-store/create-test.js
> +    await click('[value="static"]');
Great Idea!

2022-07-25 21:44 UTC, cameronperera approved these changes
LGTM

2022-07-26 16:09 UTC, DhariniJeeva approved these changes

2022-07-26 17:02 UTC, merged