feat: 🎸 Update Detail Page to show Tags
hashicorp/boundary-ui pull request #1327
Opened 2022-09-15 21:01 UTC by dvonanderson

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6037)

## Description

The read-only worker tags in detailed view will now be displayed in a `key:value` pair format.
- (note) I used [ICU-6035-update-tags-in-list-view](https://github.com/hashicorp/boundary-ui/pull/1326) locally to build this out, so current view may not look the same due to changes to mirage data.

### Screenshots (if appropriate):

<img width="1527" alt="Screen Shot 2022-09-15 at 16 52 40" src="https://user-images.githubusercontent.com/24277002/190507340-d2b4f8c8-a3a5-46c1-ba6c-49ef6164cb89.png">

2022-09-16 14:19 UTC, ZedLi requested changes

2022-09-16 14:19 UTC, ZedLi commented on addons/core/translations/form/en-us.yaml
> +worker_tags:
I think we already have a translation for [worker tags](https://github.com/hashicorp/boundary-ui/blob/main/addons/core/translations/resources/en-us.yaml#L481) and the help text.

Maybe we should check in with what text we should stick with and be consistent.

2022-09-16 14:19 UTC, ZedLi commented on ui/admin/app/components/form/worker/index.hbs
> +                  @value={{value}}
Can we display the tags with spaces between the commas rather than just outputting the array?

2022-09-19 14:40 UTC, ZedLi commented on ui/admin/app/components/form/worker/index.hbs
> +    <:description>{{t 'form.worker_tags.help'}}</:description>
I think these translation lookups need to be updated

2022-09-19 19:52 UTC, lisbet-alvarez approved these changes

2022-09-20 13:11 UTC, merged