feat: 🎸 Add optional icon for dropdown section
hashicorp/boundary-ui pull request #1332
Opened 2022-09-16 20:15 UTC by ZedLi

## Description
Add the ability to include an optional icon for dropdown sections.

### Screenshots (if appropriate):
<img width="380" alt="image" src="https://user-images.githubusercontent.com/5783847/190725285-06546486-a7ac-4c8a-9327-ee657a3fa960.png">

2022-09-16 21:04 UTC, randallmorey requested changes
Can this be added to the storybook story for dropdown?

2022-09-19 19:01 UTC, dvonanderson approved these changes
Nice

2022-09-19 19:08 UTC, lisbet-alvarez approved these changes

2022-09-19 19:43 UTC, cameronperera approved these changes

2022-09-19 20:08 UTC, DhariniJeeva approved these changes

2022-09-19 20:28 UTC, merged