refactor: 💡 hosts read acceptance tests
hashicorp/boundary-ui pull request #1401
Opened 2022-10-27 23:12 UTC by lisbet-alvarez

✅ Closes: ICU-6545

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/JIRA_TICKET_NUMBER)

## Description
Refactor host read acceptance tests to simulate user clicking in the UI

2022-10-28 16:19 UTC, ZedLi requested changes
Looks good, same comments as the host catalogs PR

2022-10-28 16:19 UTC, ZedLi commented on ui/admin/tests/acceptance/host-catalogs/hosts/read-test.js
> +    );
Also think this could've been:
```suggestion
    assert.dom('.rose-message-subtitle').hasText('Error 404');
```

2022-10-28 16:19 UTC, ZedLi commented on ui/admin/tests/acceptance/host-catalogs/hosts/read-test.js
> +  test('cannot navigate to a host form without proper authorization', async function (assert) {
Same thing here, I feel like we should also test we can't visit `hosts` as well without proper permissions.

2022-10-28 21:55 UTC, lisbet-alvarez commented on ui/admin/tests/acceptance/host-catalogs/hosts/read-test.js
> +    instances.hostCatalog.authorized_collection_actions['hosts'] = [];
```suggestion
    instances.hostCatalog.authorized_collection_actions.hosts = [];
```

2022-10-31 15:50 UTC, cameronperera commented on ui/admin/tests/acceptance/host-catalogs/hosts/read-test.js
> +    instances.hostCatalog.authorized_collection_actions.hosts = [];
Same suggestion here for using the filter method.

2022-11-01 17:19 UTC, DhariniJeeva approved these changes

2022-11-01 21:56 UTC, ZedLi approved these changes

2022-11-01 22:06 UTC, cameronperera approved these changes

2022-11-02 16:49 UTC, merged