chore: 🤖 deprecation workflow
hashicorp/boundary-ui pull request #1462
Opened 2022-11-14 22:01 UTC by DhariniJeeva

This pr introduces a rose component deprecation workflow by leveraging `ember-cli-deprecation-workflow` addon. 

This addon provides 3 options - `silence, log, throw`. Currently, for the badge component, it is set to `log`. After we migrate all of the instances of a rose component, we can move this option to `silence` to silence all the deprecation warnings.

2022-11-15 15:59 UTC, cameronperera approved these changes

2022-11-15 17:28 UTC, randallmorey requested changes

2022-11-15 18:46 UTC, DhariniJeeva commented on addons/rose/addon/components/rose/badge/index.js
> +      {
done!

2022-11-15 19:13 UTC, calcaide approved these changes
LGTM!
As a none blocking comment: Do you mind providing a screenshot of how the deprecation message looks like?

2022-11-15 19:19 UTC, DhariniJeeva commented
> LGTM! As a none blocking comment: Do you mind providing a screenshot of how the deprecation message looks like?

added to the description!

2022-11-15 20:25 UTC, ZedLi approved these changes

2022-11-16 03:28 UTC, randallmorey approved these changes

2022-11-16 03:36 UTC, merged