refactor: 💡 adjust css selector for specific asserts
hashicorp/boundary-ui pull request #1468
Opened 2022-11-15 00:22 UTC by lisbet-alvarez

✅ Closes: ICU-6889

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6889)

## Description
Refactor css selector to be more specific for assert statements that use .doesNotExist() method

2022-11-15 00:28 UTC, randallmorey requested changes

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/credential-store/credentials/list-test.js
> +    assert.dom(`.rose-nav-tabs a[href="${urls.credentials}"]`).doesNotExist();
```suggestion
    assert.dom(`.rose-nav-tabs [href="${urls.credentials}"]`).doesNotExist();
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/credential-store/credentials/read-test.js
> +      .dom(`.rose-table a[href="${urls.usernamePasswordCredential}"]`)
```suggestion
      .dom(`.rose-table [href="${urls.usernamePasswordCredential}"]`)
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/credential-store/read-test.js
> +      .dom(`.rose-table a[href="${urls.staticCredentialStore}"]`)
```suggestion
      .dom(`.rose-table [href="${urls.staticCredentialStore}"]`)
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/credential-store/read-test.js
> +      .dom(`.rose-table a[href="${urls.unknownCredentialStore}"]`)
```suggestion
      .dom(`.rose-table [href="${urls.unknownCredentialStore}"]`)
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/host-catalogs/host-sets/read-test.js
> +    assert.dom(`.rose-table a[href="${urls.hostSet}"]`).doesNotExist();
```suggestion
    assert.dom(`.rose-table [href="${urls.hostSet}"]`).doesNotExist();
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/host-catalogs/host-sets/read-test.js
> +    assert.dom(`.rose-table a[href="${urls.unknownHostSet}"]`).doesNotExist();
```suggestion
    assert.dom(`.rose-table [href="${urls.unknownHostSet}"]`).doesNotExist();
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/host-catalogs/hosts/read-test.js
> +    assert.dom(`.rose-table a[href="${urls.host}"]`).doesNotExist();
```suggestion
    assert.dom(`.rose-table [href="${urls.host}"]`).doesNotExist();
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/host-catalogs/hosts/read-test.js
> +    assert.dom(`.rose-table a[href="${urls.unknownHost}"]`).doesNotExist();
```suggestion
    assert.dom(`.rose-table [href="${urls.unknownHost}"]`).doesNotExist();
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/host-catalogs/read-test.js
> +    assert.dom(`.rose-table a[href="${urls.hostCatalog}"]`).doesNotExist();
```suggestion
    assert.dom(`.rose-table [href="${urls.hostCatalog}"]`).doesNotExist();
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/host-catalogs/read-test.js
> +      .dom(`.rose-table a[href="${urls.unknownHostCatalog}"]`)
```suggestion
      .dom(`.rose-table [href="${urls.unknownHostCatalog}"]`)
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/sessions-test.js
> +    assert.dom(`nav:nth-child(2) a[href="${urls.sessions}"]`).doesNotExist();
```suggestion
    assert.dom(`nav:nth-child(2) [href="${urls.sessions}"]`).doesNotExist();
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/targets/brokered-credential-sources-test.js
> +        `.rose-dropdown-content a[href="${urls.addBrokeredCredentialSources}"]`
```suggestion
        `.rose-dropdown-content [href="${urls.addBrokeredCredentialSources}"]`
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/targets/read-test.js
> +    assert.dom(`.rose-table a[href="${urls.sshTarget}"]`).doesNotExist();
```suggestion
    assert.dom(`.rose-table [href="${urls.sshTarget}"]`).doesNotExist();
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/targets/read-test.js
> +    assert.dom(`.rose-table a[href="${urls.tcpTarget}"]`).doesNotExist();
```suggestion
    assert.dom(`.rose-table [href="${urls.tcpTarget}"]`).doesNotExist();
```

2022-11-15 00:28 UTC, randallmorey commented on ui/admin/tests/acceptance/targets/read-test.js
> +    assert.dom(`.rose-table a[href="${urls.unknownTarget}"]`).doesNotExist();
```suggestion
    assert.dom(`.rose-table [href="${urls.unknownTarget}"]`).doesNotExist();
```

2022-11-15 15:32 UTC, cameronperera commented on ui/admin/tests/acceptance/credential-store/credentials/read-test.js
> +      .dom(`.rose-table a[href="${urls.usernameKeyPairCredential}"]`)
```suggestion
      .dom(`.rose-table [href="${urls.usernameKeyPairCredential}"]`)
```

2022-11-15 15:33 UTC, cameronperera commented on ui/admin/tests/acceptance/credential-store/read-test.js
> +      .dom(`.rose-table a[href="${urls.vaultCredentialStore}"]`)
```suggestion
      .dom(`.rose-table [href="${urls.vaultCredentialStore}"]`)
```

2022-11-15 19:45 UTC, calcaide requested changes
Everything LGTM but I do agree on Cameron's suggestiong to change.

2022-11-15 21:09 UTC, ZedLi commented
Sorry what was the issue with checking for the attribute on the `a` element?

Unrelated to that issue, I actually don't think there's too much value in making it more specific just to the table. I think it's the value is in checking for the specific row we're expecting it to be in, though I can see how that much might be much harder to change for all of these.

2022-11-15 21:38 UTC, randallmorey commented
> Sorry what was the issue with checking for the attribute on the `a` element?
> 
> Unrelated to that, I actually don't think there's too much value in making it more specific just to the table either way. I think the issue still remains in that if we mess up the URL/href, we might be _thinking_ we're checking that it doesn't exist correctly but really we just got the URL wrong.
> 
> I think what is a more accurate test would be checking specifically for an `a` element (with no url attribute) inside a row/cell of the table. There shouldn't be an `a` link if we don't have permission.

Ah good point.  Proving absence needs more thought.

For selectors, it's generally better to use the least specific selector possible.  In CSS the reason is to avoid a specificity race.  In JavaScript, less specific selectors are less likely to break when markup changes are made.

Ultimately we need to rethink test selectors.  I know a number of other product teams use `data-` attributes to directly mark elements of interest.

2022-11-15 21:59 UTC, ZedLi commented
> For selectors, it's generally better to use the least specific selector possible. In CSS the reason is to avoid a specificity race. In JavaScript, less specific selectors are less likely to break when the markup changes.
> 
> Ultimately we need to rethink test selectors. I know a number of other product teams use `data-` attributes to directly mark elements of interest.

Yup totally agree with both points here, I think that's why I was originally thinking of just checking for `a`. I think this is a good topic to have in tech time, I added it as I do think we should talk about it more

2022-11-16 17:37 UTC, lisbet-alvarez commented
> > For selectors, it's generally better to use the least specific selector possible. In CSS the reason is to avoid a specificity race. In JavaScript, less specific selectors are less likely to break when the markup changes.
> > Ultimately we need to rethink test selectors. I know a number of other product teams use `data-` attributes to directly mark elements of interest.
> 
> Yup totally agree with both points here, I think that's why I was originally thinking of just checking for `a` rather than a URL. I think this is a good topic to have in tech time, I added it as I do think we should talk about it more

Very good points were brought up. For now, I will convert this to a draft PR and I will attend tomorrow's tech time to discuss this topic.

2022-11-21 22:05 UTC, calcaide approved these changes
LGTM!

As mentioned in slack, this PR covers what is need and we will further discussion about test selectors.

2022-11-22 01:52 UTC, lisbet-alvarez commented on addons/core/tests/integration/helpers/relative-datetime-live-test.js
> +    this.date = now + 23 * 12 * 30 * 24 * 60 * 60 * 1000;
```suggestion
    this.date = now + 23 * 12 * 31 * 24 * 60 * 60 * 1000;
```

2022-11-23 20:46 UTC, ZedLi approved these changes
LGTM, thanks for this refactor!

2022-11-28 22:26 UTC, cameronperera approved these changes

2022-11-28 22:44 UTC, merged