feat: 🎸 Custom information field
hashicorp/boundary-ui pull request #1493
Opened 2022-11-22 18:13 UTC by dvonanderson

✅ Closes: ICU-6881 ICU-6957

:tickets: [ICU-6881](https://hashicorp.atlassian.net/browse/ICU-6881), [ICU-6957](https://hashicorp.atlassian.net/browse/ICU-6957) 

## Description
Create custom information component for views that need read-only information listed.

:technologist: [Admin preview](https://www.figma.com/file/BB6W9sZwp75aOsXgCN8ecb/JSON-Credentials?node-id=1661%3A2780&t=yea0Yqe2Ah1p9PT9-0)

### Screenshots (if appropriate):
## Previous look gave us a disabled radio card.
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/24277002/203389089-b0147f57-98e3-4cb7-8eee-fb4bb581eef2.png">

### New info-field component.
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/24277002/203388772-b237f4b1-58dd-406d-8825-38b9be3a009a.png">

### If needed we can add a icon next to the label text
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/24277002/203389623-5dc0c1ab-f3a2-41d4-b38b-30323c609e69.png">

2022-11-22 20:56 UTC, randallmorey requested changes
I like how you integrated the icon into the component!  Only feedback is to tweak the layout/spacing when the icon is visible to align with the original design.  If possible, can we make the input color darker too?

2022-11-22 21:12 UTC, dvonanderson commented
> I like how you integrated the icon into the component! Only feedback is to tweak the layout/spacing when the icon is visible to align with the original design. If possible, can we make the input color darker too?

Yes absolutely!

2022-11-23 16:49 UTC, calcaide commented on ui/admin/app/components/info-field/index.hbs
> +<div class='info-field'>
Good catch, I miss that one

2022-11-23 16:50 UTC, dvonanderson commented on ui/admin/app/components/info-field/index.hbs
> +<div class='info-field'>
yes Absolutely!

2022-11-23 20:02 UTC, DhariniJeeva approved these changes

2022-11-29 15:41 UTC, cameronperera approved these changes
LGTM

2022-11-30 17:57 UTC, cameronperera commented on ui/admin/app/components/form/credential-store/static/index.hbs
> +        disabled={{form.disabled}}
Should InfoField be disabled by default? Even when editing, we do not allow resources to change their type.

2022-11-30 19:38 UTC, merged