feat: 🎸 Give more instructions for how to connect to tunnel
hashicorp/boundary-ui pull request #1515
Opened 2022-12-07 00:01 UTC by ZedLi

✅ Closes: ICU-6527

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-6527)

## Description

Updated the desktop client connect to give more instructions on what to do with the localhost tunnel.

### Screenshots (if appropriate):
light mode:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/5783847/206051415-2bd9de66-45f3-4329-a74f-c3d3f8b1fd14.png">

dark mode:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/5783847/206051875-7e28a9e1-295b-4774-bfe6-ed269edf2a76.png">

2022-12-07 15:11 UTC, dvonanderson approved these changes

2022-12-10 17:26 UTC, randallmorey requested changes

2022-12-10 17:26 UTC, randallmorey commented on ui/desktop/app/templates/scopes/scope/projects/targets.hbs
> +            {{#if (eq target.type 'ssh')}}
```suggestion
            {{#if target.isSSH}}
```

2022-12-13 19:05 UTC, calcaide approved these changes

2022-12-13 20:24 UTC, randallmorey approved these changes

2022-12-13 21:58 UTC, cameronperera approved these changes

2022-12-13 22:21 UTC, ZedLi commented
There's currently a bug where the copy function doesn't work in desktop, will investigate later why it doesn't work

2022-12-14 05:57 UTC, randallmorey requested changes
> There's currently a bug where the copy function doesn't work in desktop, will investigate later why it doesn't work

Rose code editor has a reference to a `CopyButton` component.  This component does not appear to be extant.  In any case, the code editor may be too peculiar for Rose itself.  I wonder if code editor can be moved into admin and desktop, and changed to use `Copyable`.

Currently, admin and desktop have their own copies of a `Copyable` component, which is not available in Rose because it does not originate from Structure.  It may make sense to promote Copyable to addons/core, provided sufficient tests can be added.  However, Rose Code Editor is relatively new and differs enough from existing patterns that I recommend it remain within the UIs for now.

https://github.com/hashicorp/boundary-ui/blame/main/addons/rose/addon/components/rose/code-editor/toolbar/index.hbs#L19

2022-12-14 15:28 UTC, ZedLi commented
> This component does not appear to be extant

What do you mean by it's not extant? It comes from this [package](https://github.com/jkusa/ember-cli-clipboard). I had [looked at it before](https://github.com/hashicorp/boundary-ui/pull/1207#discussion_r932768848) and it was similar to our `Copyable` and both are using ClipboardJS under the hood, but this one had the benefit of having test coverage so it seemed like a good thing to replace what we were already using.

Is this something we want to discuss more in tech time?

2022-12-16 18:47 UTC, randallmorey approved these changes

2023-01-12 19:57 UTC, closed without merging