Add mirage support principal managed groups
hashicorp/boundary-ui pull request #1542
Opened 2022-12-21 00:14 UTC by DhariniJeeva

This PR adds mocks for managed groups in `role/principals list` and `add to principals` view for both global and org-level scope. 

This is part of https://hashicorp.atlassian.net/browse/ICU-7102 

global scope: 
<img width="836" alt="Screen Shot 2022-12-20 at 1 37 24 PM" src="https://user-images.githubusercontent.com/15043878/208790709-c42589c1-5c68-4a8c-98c9-101ace0343e4.png">

org Scope: 
<img width="931" alt="Screen Shot 2022-12-20 at 1 36 50 PM" src="https://user-images.githubusercontent.com/15043878/208790725-4fa07e77-271a-403f-90bc-659fdfb3e5e4.png">

2022-12-21 15:09 UTC, randallmorey requested changes
Made some minor suggestions.  One question I had is why model managed groups with a `scope`?  IIRC this doesn't appear in the API.

2022-12-21 15:09 UTC, randallmorey commented on addons/api/mirage/factories/role.js
> +        .models.map((model) => model);
```suggestion
        .models;
```

2022-12-21 15:09 UTC, randallmorey commented on addons/api/mirage/scenarios/default.js
> +  const OrgScopeRoles = server.createList(
```suggestion
  const orgScopeRoles = server.createList(
```

2022-12-21 15:09 UTC, randallmorey commented on addons/api/mirage/scenarios/default.js
> +  OrgScopeRoles.forEach((role) => {
```suggestion
  orgScopeRoles.forEach((role) => {
```

2022-12-21 15:09 UTC, randallmorey commented on addons/api/mirage/scenarios/default.js
> +    );
```suggestion
    )[0];
```

2022-12-21 15:09 UTC, randallmorey commented on addons/api/mirage/scenarios/default.js
> +      authMethodId: oidcAuthMethod[0].id,
```suggestion
      authMethodId: oidcAuthMethod.id,
```

2022-12-21 17:40 UTC, DhariniJeeva commented
> Made some minor suggestions. One question I had is why model managed groups with a `scope`? IIRC this doesn't appear in the API.

ah, you are right. we don't need scope id for the managed group, updated!

2022-12-21 17:50 UTC, DhariniJeeva commented
> Made some minor suggestions. One question I had is why model managed groups with a `scope`? IIRC this doesn't appear in the API.

actually that's a valid point, I'm double checking if everything works without the scope Id since this was already there in the code

2022-12-21 20:32 UTC, DhariniJeeva commented
> > Made some minor suggestions. One question I had is why model managed groups with a `scope`? IIRC this doesn't appear in the API.
> 
> actually that's a valid point, I'm double checking if everything works without the scope Id since this was already there in the code

After an offline discussion, it is understood that we add scopes to managed groups.

2022-12-22 16:41 UTC, ZedLi approved these changes

2022-12-22 18:23 UTC, merged