chore: 🤖 Update changelog and version for desktop client
hashicorp/boundary-ui pull request #1625
Opened 2023-02-06 21:56 UTC by ZedLi

## Description
Update the changelog and version in desktop client for 0.12. 
Will merge when 0.12 OSS is released.

2023-02-06 22:01 UTC, cameronperera approved these changes

2023-02-07 16:25 UTC, calcaide approved these changes

2023-02-08 19:43 UTC, randallmorey requested changes

2023-02-08 19:43 UTC, randallmorey commented on ui/desktop/CHANGELOG.md
> +- Upgrade CLI to v0.12.0
```suggestion
- Upgrade CLI to v0.12.0 ([PR](https://github.com/hashicorp/boundary-ui/pull/1625))
```

2023-02-13 19:18 UTC, merged