Target form refactor
hashicorp/boundary-ui pull request #1627
Opened 2023-02-08 17:55 UTC by DhariniJeeva

2023-02-08 18:06 UTC, randallmorey requested changes

2023-02-08 18:06 UTC, randallmorey commented on ui/admin/app/components/form/target/details/index.js
> +  //this part is deprecated and will eventually be retired
```suggestion
  // These methods may be removed after the `worker_filter` field is removed from the API.

```

2023-02-08 18:06 UTC, randallmorey commented on ui/admin/app/components/form/target/details/index.js
> +   * determines when the worker filter deprecation message should be shown
```suggestion
   * Evaluates to `true` if the worker filter deprecation message should be shown.
```

2023-02-08 18:06 UTC, randallmorey commented on ui/admin/app/components/form/target/details/index.js
> +  @action
```suggestion

  /**
   * Copies the value from `worker_filter` into `egress_worker_filter` and `ingress_worker_filter`
   * and unsets `worker_filter`.
   */
  @action
```

2023-02-10 15:50 UTC, cameronperera approved these changes
LGTM

2023-02-10 16:31 UTC, ZedLi approved these changes

2023-02-10 22:38 UTC, merged