feat: 🎸 initial LDAP authentication support
hashicorp/boundary-ui pull request #1645
Opened 2023-02-24 22:00 UTC by randallmorey

Basic LDAP authentication support.

2023-05-10 22:16 UTC, DhariniJeeva commented on addons/core/addon/components/form/authenticate/index.hbs
> -    cancel=false
I removed this as we don't have a cancel button on the authenticate forms

2023-05-11 15:00 UTC, cameronperera requested changes

2023-05-11 15:00 UTC, cameronperera commented on addons/core/tests/integration/components/form/authenticate-test.js
> +module('Integration | Component | form | authenticate', function (hooks) {
Could we add a some more tests/asserts for this form? My thoughts are with the current test, we could delete the 2 input fields and this tests would still pass. My suggestion would be to assert the inputs and form buttons are present.

2023-05-11 19:49 UTC, lisbet-alvarez approved these changes
LGTM!

2023-05-11 20:54 UTC, cameronperera approved these changes
Looks great!

2023-05-11 20:55 UTC, merged