chore: Use HDS components in auth methods list view
hashicorp/boundary-ui pull request #1686
Opened 2023-05-12 04:33 UTC by DhariniJeeva

This pr updates auth method list table and dropdown and notification to HDS components

Before: (Rose)

<img width="1253" alt="Screenshot 2023-05-11 at 9 26 23 PM" src="https://github.com/hashicorp/boundary-ui/assets/15043878/857c7a0b-5e89-4f69-9ce1-004f8a2f9cdd">

<img width="1254" alt="Screenshot 2023-05-11 at 9 26 18 PM" src="https://github.com/hashicorp/boundary-ui/assets/15043878/899ef42b-6daf-47e2-90a7-5dc0fca590d4">

After:(HDS)
<img width="1260" alt="Screenshot 2023-05-11 at 5 17 07 PM" src="https://github.com/hashicorp/boundary-ui/assets/15043878/f91417cd-a932-4d42-b746-ca81cefb03d6">

<img width="1264" alt="Screenshot 2023-05-11 at 5 17 12 PM" src="https://github.com/hashicorp/boundary-ui/assets/15043878/a8027503-8d3a-424c-82e6-a11dc65d45d5">

<img width="1259" alt="Screenshot 2023-05-11 at 5 17 19 PM" src="https://github.com/hashicorp/boundary-ui/assets/15043878/af220e06-2ebc-4697-9126-26805ce6cc7f">

2023-05-12 15:09 UTC, cameronperera approved these changes
LGTM

2023-05-12 15:25 UTC, ZedLi requested changes

2023-05-12 21:42 UTC, DhariniJeeva commented on ui/admin/app/templates/scopes/scope/auth-methods/index.hbs
> -                <p>{{authMethod.description}}</p>
Done! thanks for the catch

2023-05-15 18:01 UTC, ZedLi approved these changes
Looks great!

2023-05-16 16:14 UTC, lisbet-alvarez approved these changes
LGTM!

2023-05-16 16:37 UTC, merged