chore: 🤖 Retire rose form textarea
hashicorp/boundary-ui pull request #1735
Opened 2023-06-21 19:47 UTC by NatashaKab

✅ Closes: ICU-9425

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9425)

## Description
Retire rose form textarea

:rose: [Rose preview](PATH_TO_FEATURE)

2023-06-21 19:47 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/boundary-ui?pullRequest=1735)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/boundary-ui?pullRequest=1735)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/boundary-ui?pullRequest=1735).</sub>

2023-06-29 21:53 UTC, lisbet-alvarez approved these changes
Amazing work! Looks great!

2023-06-30 17:44 UTC, DhariniJeeva commented on addons/rose/addon/components/rose/form/index.stories.mdx
> +        <Hds::Form::Textarea::Field @value="This is my description" as |F|>
This should include `disabled={{form.disabled}}`, same as the below select field to show the usage

2023-06-30 17:44 UTC, DhariniJeeva commented on addons/rose/addon/components/rose/form/index.stories.mdx
> +  <Hds::Form::Textarea::Field @value='This is my description' as |F|>
This should include disabled={{form.disabled}}, same as the below select field to show the usage

2023-06-30 17:44 UTC, DhariniJeeva commented on addons/rose/tests/integration/components/rose/form-test.js
> +        <Hds::Form::Textarea::Field @value="This is my description" name="textarea-field" as |F|>
This should include disabled={{form.disabled}}, same as the below select field to show the usage

2023-06-30 17:45 UTC, DhariniJeeva commented on addons/rose/addon/components/rose/form/textarea/index.stories.mdx
> +<Hds::Form::Textarea::Field @value='This is my description' as |F|>
This should include disabled={{form.disabled}} to show the usage

2023-06-30 17:47 UTC, DhariniJeeva requested changes
can we include the usage of the `disabled` attribute in the textarea storybook similar to the select field?

2023-07-04 17:28 UTC, calcaide requested changes
+1 to @DhariniJeeva comments. Great job Natasha!! looking good 😃

2023-07-07 18:26 UTC, calcaide approved these changes
Let's goooo @NatashaKab !!! great job!! 💪

2023-07-07 21:23 UTC, DhariniJeeva approved these changes

2023-07-07 22:03 UTC, ZedLi approved these changes

2023-07-10 19:30 UTC, merged