Icu 9881 remove use of rose form textarea from admin UI
hashicorp/boundary-ui pull request #1744
Opened 2023-06-23 20:48 UTC by NatashaKab

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-9881)

## Description
remove use of rose form textarea from admin UI

This pull request will unblock the pull request to [retire rose textarea.](https://github.com/hashicorp/boundary-ui/pull/1735)

2023-06-26 15:41 UTC, ZedLi requested changes

2023-06-26 15:41 UTC, ZedLi commented on ui/admin/app/components/form/auth-method/oidc/index.hbs
> +                <Hds::Form::Textarea::Field
I believe this is also optional

2023-06-26 15:41 UTC, ZedLi commented on ui/admin/app/components/form/credential-store/vault/index.hbs
> +  <Hds::Form::Textarea::Field
Any reason we didn't mark any of these text areas as optional? I believe these are all optional

2023-06-26 15:41 UTC, ZedLi commented on ui/admin/app/components/form/host-set/azure/index.hbs
>    <form.textarea
Looks like this didn't get deleted?

2023-06-26 15:41 UTC, ZedLi commented on ui/admin/app/components/form/host-set/azure/index.hbs
> +  <Hds::Form::Textarea::Field
I think this is also optional

2023-06-26 17:55 UTC, calcaide requested changes
Terrific work @NatashaKab !!  those new text areas looking great!!

Almost done!! I +1 @ZedLi comment about `isOptional` and `isRequired` and the missing one within azure host-sets (left specific comment).
Appreciate the hard work!!

2023-06-27 18:12 UTC, DhariniJeeva approved these changes
Great job! LGTM!

2023-06-27 18:52 UTC, DhariniJeeva requested changes
We found that some new textarea fields aren't disabled in edit mode.

2023-06-28 19:36 UTC, DhariniJeeva approved these changes

2023-06-28 21:05 UTC, ZedLi approved these changes
Looks great!

2023-06-28 22:04 UTC, calcaide approved these changes
Let's gooo @NatashaKab !! great job :partying_face:

2023-06-28 22:05 UTC, merged