Icu 12782 add filtering pagination support for credential stores
hashicorp/boundary-ui pull request #2212
Opened 2024-04-01 23:57 UTC by lisbet-alvarez

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12782

:tickets: [Jira ticket](https://hashicorp.atlassian.net/browse/ICU-12782)

## Description

## Screenshots (if appropriate):

## How to Test

:technologist: [Admin preview](PATH_TO_FEATURE)

:desktop_computer: [Desktop preview](PATH_TO_FEATURE)

## Checklist:

- [ ] I have added before and after screenshots for UI changes
- [ ] I have added JSON response output for API changes
- [ ] I have added steps to reproduce and test for bug fixes in the description
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-04-02 18:52 UTC, ZedLi commented on ui/admin/tests/acceptance/credential-store/list-test.js
> +  test('user can search for a specifc credential-store by id', async function (assert) {
```suggestion
  test('user can search for a specific credential-store by id', async function (assert) {
```

2024-04-02 22:40 UTC, ZedLi approved these changes
Looks great!!

2024-04-03 19:20 UTC, cameronperera requested changes

2024-04-03 19:20 UTC, cameronperera commented on ui/admin/app/routes/scopes/scope/credential-stores/index.js
> +   * active sessions filtering options.
I think this mention of active sessions is not needed?

2024-04-04 14:43 UTC, cameronperera approved these changes

2024-04-04 16:19 UTC, merged