refactor: 💡 remove route-action usage for workers
hashicorp/boundary-ui pull request #2302
Opened 2024-05-21 18:13 UTC by lisbet-alvarez

✅ Closes: https://hashicorp.atlassian.net/browse/ICU-12613

# Description

Remove route-action usage for workers. The only route-action usage that was not removed was the actions used for tag filtering because that will be replaced by worker tag ux improvements in the future.

## Screenshots (if appropriate)

## How to Test

1. start boundary dev instance
2. test editing and deleting an existing worker
3. start boundary server instance in order to get a registration token
4. use token to create a worker (make sure cancel and done buttons behave as intended in pki worker creation form)

## Checklist

- [ ] I have added before and after screenshots for UI changes
- [ ] I have added JSON response output for API changes
- [ ] I have added steps to reproduce and test for bug fixes in the description
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

2024-05-29 20:57 UTC, calcaide commented on ui/admin/app/routes/scopes/scope/workers.js
>    // =services
Do we need to keep service `router`?

2024-05-29 21:03 UTC, calcaide requested changes
I tested, successfully editing and deleting a worker.

Awesome job!!!

Do you mind providing the procedure or instructions to create a worker within the development environment?

2024-05-31 15:01 UTC, calcaide approved these changes
Amazing work @lisbet-alvarez 

Ignore my previous message 😅 as @DhariniJeeva suggested, I just follow the form instructions and got a worker up and running, my bad.

Thank you for this work 💪

2024-06-04 16:57 UTC, cameronperera approved these changes

2024-06-10 23:50 UTC, lisbet-alvarez commented on ui/admin/app/routes/scopes/scope/workers.js
>    // =services
yup still needed on line 24

2024-06-11 00:12 UTC, merged