feat: Add List::Value component to rose addon
hashicorp/boundary-ui pull request #538
Opened 2021-04-21 18:06 UTC by gsusmi

Introduces a new `Rose::List::Value` component based on `Rose::List::KeyValue`.
<img width="1116" alt="rose-list-value" src="https://user-images.githubusercontent.com/111036/115600434-b33a1400-a2aa-11eb-934a-8b7d6cc8b46b.png">

2021-04-21 18:07 UTC, gsusmi commented on addons/rose/addon/components/rose/list/value/item/index.hbs
> +<li class="rose-list-value-item" id={{concat "item-value-" this.id}}>
Struggled a bit here to find an aria label to add. Ended up with using an unique id coz there isn't a label within this component, unless a `title` or `label` can be passed in. Thoughts?

2021-04-28 20:57 UTC, randallmorey requested changes
Sorry to keep bouncing around on the naming.  At its core, this is not a form-specific list.  Can this be rethought?

I'd also like to see a bit more description in the story that explains the separated appearance, as well as the way that `cell` works.

2021-04-30 20:43 UTC, randallmorey requested changes

2021-04-30 20:43 UTC, randallmorey commented on addons/rose/addon/components/rose/form/list/index.hbs
> +<ul class="rose-form-list"
Should this component go away?

2021-04-30 20:43 UTC, randallmorey commented on addons/rose/addon/components/rose/list/separated/index.stories.mdx
> +<Meta title="Rose|Form/List" component="Form/List" />
Naming.

2021-04-30 20:43 UTC, randallmorey commented on addons/rose/addon/components/rose/list/separated/index.stories.mdx
> +<Rose::Form::List @label="list-example" as |list|>
Naming.

2021-04-30 20:43 UTC, randallmorey commented on addons/rose/addon/components/rose/list/separated/index.stories.mdx
> +    <Rose::Form::List @label="list-example" as |list|>
Naming.

2021-04-30 20:43 UTC, randallmorey commented on addons/rose/tests/dummy/app/templates/index.hbs
> +  <Rose::Form as |form|>
Minor point but I'd swap the order here.  Form should be the parent of list.

2021-04-30 20:43 UTC, randallmorey commented on addons/rose/tests/integration/components/rose/form/list-test.js
> +module('Integration | Component | rose/form/list', function (hooks) {
Isn't the form list going away?

2021-04-30 20:46 UTC, gsusmi commented
Moving into draft. Apologies @randallmorey, this was still in-progress but I forgot to update PR.

2021-05-03 19:39 UTC, gsusmi commented
Closing in favor of updating table component styles.

2021-05-03 19:39 UTC, closed without merging