Add Credential Store Attributes
hashicorp/boundary-ui pull request #675
Opened 2021-07-27 18:31 UTC by gsusmi

2021-07-27 21:44 UTC, calcaide approved these changes
LGTM

2021-07-28 14:17 UTC, randallmorey requested changes
We should probably display the HMAC values (token, client cert key) in read-only fields to be consistent with the OIDC form.

Also, the fields which have associated HMAC values (token, client cert) may need to be deleted from the serialisation when they are falsy.  This is always true for token (it may not be unset).  And sometimes true for client cert key (it may not be unset as long as client cert has a value).

2021-07-28 17:24 UTC, gsusmi commented
Updates:
#### Edit mode for credential store displays HMAC values for token and client certificate key:
![screencapture-localhost-4032-scopes-s-xk1i4dk50v2-credential-stores-credential-store-id-0-2021-07-28-13_09_16](https://user-images.githubusercontent.com/111036/127368289-382bddcb-c27d-4318-ac85-84ca4bb50866.png)


#### Fix: TLS skip verify checkbox error handler
<img width="797" alt="Screen Shot 2021-07-28 at 13 12 22" src="https://user-images.githubusercontent.com/111036/127368298-f7cb022c-da75-4ab0-8ea1-b99dfc729937.png">

2021-07-29 13:31 UTC, randallmorey approved these changes

2021-07-29 13:33 UTC, merged