refactor: 💡 Change credential stores strings
hashicorp/boundary-ui pull request #679
Opened 2021-07-28 22:23 UTC by calcaide

Change credential stores strings for credential sources.

✅ Closes: ICU-2039

Screenshoots of the change. If you see a missing string change please let me know and I will add it to this PR.

<img width="1505" alt="Screen Shot 2021-07-28 at 3 12 10 PM" src="https://user-images.githubusercontent.com/9775006/127403881-e65d3f9b-f0af-420d-8fef-f3e5b6a18bb9.png">

<img width="1502" alt="Screen Shot 2021-07-28 at 3 13 57 PM" src="https://user-images.githubusercontent.com/9775006/127403892-e77135ad-e5e8-4ce6-918b-af227727a7c2.png">

2021-07-28 23:08 UTC, DhariniJeeva commented
for parity, could we also update the folder/file names? (maybe after release?)

2021-07-28 23:15 UTC, DhariniJeeva approved these changes
LGTM!

2021-07-29 13:00 UTC, gsusmi requested changes
The API is moving towards using "credential source" instead of "credential library". This PR is renaming "credential store" into "credential source". Could we recheck the requirement please?

2021-07-29 13:44 UTC, randallmorey requested changes
@gsusmi is right.  The change is Library -> Source.  "Store" remains the same.

2021-07-29 14:22 UTC, calcaide commented
:trollface: my bad. I am going to close this branch and PR and open one for do the change of "Credential library" to "Credential Source"

2021-07-29 14:25 UTC, closed without merging