fix: 🐛 Fix missing translation
hashicorp/boundary-ui pull request #870
Opened 2021-11-23 15:54 UTC by calcaide

Fix missing translation for hosts list within host-catalog.

Without the fix:
<img width="1502" alt="Screen Shot 2021-11-23 at 7 51 53 AM" src="https://user-images.githubusercontent.com/9775006/143057766-a8c0ff67-d3f0-41bd-9a62-f41f3b09d7ab.png">

With the fix
<img width="1505" alt="Screen Shot 2021-11-23 at 7 53 38 AM" src="https://user-images.githubusercontent.com/9775006/143057915-f0e4e948-398b-4c2f-95cb-1b22bfc3ed42.png">

2021-11-23 16:59 UTC, DhariniJeeva reviewed
looks good! ty for fixing this. could we include the dev links to the pr?

2021-11-23 17:26 UTC, calcaide commented
> looks good! ty for fixing this. could we include the dev links to the pr?

Thanks @DhariniJeeva ! what do you mean by dev links?

2021-11-23 17:28 UTC, DhariniJeeva commented
> > looks good! ty for fixing this. could we include the dev links to the pr?
> 
> Thanks @DhariniJeeva ! what do you mean by dev links?

the deployed vercel preview linked to the screenshot above

2021-11-23 18:24 UTC, calcaide commented
> > > looks good! ty for fixing this. could we include the dev links to the pr?
> > 
> > 
> > Thanks @DhariniJeeva ! what do you mean by dev links?
> 
> the deployed vercel preview linked to the screenshot above

lol I name it differently, but good catch forgot the link! added!

2021-11-23 22:47 UTC, DhariniJeeva approved these changes
🥂

2021-11-26 17:44 UTC, randallmorey requested changes
This fixes the translation issue.  However, dynamic host catalogs work differently than static.  The host catalog UI today supports only static.  Therefore we should simply _hide_ any records that aren't of type `static`.  e.g. `{{#if hostCatalog.isStatic}} show table row here {{/if}}`

2021-11-29 21:00 UTC, calcaide commented
> This fixes the translation issue. However, dynamic host catalogs work differently than static. The host catalog UI today supports only static. Therefore we should simply _hide_ any records that aren't of type `static`. e.g. `{{#if hostCatalog.isStatic}} show table row here {{/if}}`

@randallmorey 

I see what you mean. I was looking for your feedback here.
Because we are not supporting this feature at the UI, I will close this PR.
I will provide a new one with the conditional in host catalog, as per your suggestion.

2021-11-29 21:00 UTC, closed without merging