feat: 🎸 Only support static types at hosts
hashicorp/boundary-ui pull request #875
Opened 2021-12-02 00:04 UTC by calcaide

Make sure the hosts list within a host-catalog just show rows that have a Static type.

[Direct link]().

<img width="1500" alt="Screen Shot 2021-12-01 at 4 03 41 PM" src="https://user-images.githubusercontent.com/9775006/144333854-1d5a15b1-8a9c-48e3-8f7e-e642eebbe182.png">

2021-12-02 16:48 UTC, randallmorey requested changes

2021-12-02 16:48 UTC, randallmorey commented on addons/api/addon/models/host.js
> +  get isStaticType() {
`isStatic` ought to do it and is more consistent with existing field names.

2021-12-02 16:48 UTC, randallmorey commented on addons/api/tests/unit/models/host-test.js
> +    const model = store.createRecord('host', { type: 'static' });
how about `modelA` for consistency?

2021-12-06 22:10 UTC, randallmorey requested changes
Sorry for the confusion.  The host catalog index (not the host index) should show only static host catalogs in the UI for now.

2021-12-06 22:20 UTC, calcaide commented
@randallmorey 

Ok. So we need to add the `type: static` constrain to host-catalogs list ([link here](https://boundary-ui-git-feature-host-catalog-hosts-onl-f4d92e-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/host-catalogs)) and do not add any constrain on the hosts list within a host-catalog ([link here](https://boundary-ui-git-feature-host-catalog-hosts-onl-f4d92e-hashicorp.vercel.app/scopes/s_xk1i4dk50v2/host-catalogs/1/hosts)).

Is this correct?

2021-12-06 22:34 UTC, calcaide commented
As per comments on this PR and [this slack thread](https://hashicorp.slack.com/archives/C012GTH1C4E/p1638827922072500) closing this PR to move the support static type hosts to host-catalogs index.

2021-12-06 22:34 UTC, closed without merging