feat: 🎸 Add host catalog type basic support
hashicorp/boundary-ui pull request #900
Opened 2022-01-11 23:35 UTC by calcaide

Add host catalog type basic support. Delete previous conditional rendering to just render static types.

2022-01-13 20:33 UTC, randallmorey requested changes
See review comments.  We need to support _setting_ of the `compositeType` field as well as getting.  Ideally application code doesn't interact with `plugin` field directly.

2022-01-13 20:33 UTC, randallmorey commented on addons/api/addon/models/host-catalog.js
> +  }
Let's add a `set compositeType(type)` field that handles setting values of `static` or `*`.

- If setting this field to `static`, the underlying field `type` should be set to `static`.
- For any other value, `type` should be set to `plugin` and `plugin.name` should be set to the value.

2022-01-13 20:33 UTC, randallmorey commented on addons/api/mirage/generated/factories/host-catalog.js
> +    } else {
The else is unnecessary since `undefined` is the default return value.

2022-01-14 02:35 UTC, calcaide commented on addons/api/tests/unit/models/host-catalog-test.js
> +    modelPlugin.set('compositeType', 'aws');
@randallmorey I could not find a pattern to test set in our codebase. I found this in a old ember documentation. Thoughts?

2022-01-14 18:44 UTC, randallmorey requested changes

2022-01-14 18:44 UTC, randallmorey commented on addons/api/addon/models/host-catalog.js
> +    return this.plugin.name === 'aws';
Should this use `this.compositeType`?

2022-01-14 18:44 UTC, randallmorey commented on addons/api/addon/models/host-catalog.js
> +      this.plugin.name = type;
The only time it is valid to _set_ the `plugin` field is for a new model instance.  In this case, the field is expected to be initially undefined, so it should set the whole object.

2022-01-14 18:44 UTC, randallmorey commented on addons/api/addon/models/host-catalog.js
> +      this.plugin.name = type;
If we were to ever set `plugin.id` we'd need to revisit this.  But for now I think it's fine.

2022-01-14 18:44 UTC, randallmorey commented on addons/api/mirage/generated/factories/host-catalog.js
> +        name: random.arrayElement(['azure', 'aws']),
The current index of the instance is passed into the function, so be sure to add the parameter on line 14, then:
```suggestion
        name: i % 2 ? 'aws' : 'azure',
```

2022-01-14 18:44 UTC, randallmorey commented on addons/api/tests/unit/models/host-catalog-test.js
> +      plugin: { name: 'Test name' },
```suggestion
      compositeType: 'aws',
```

2022-01-14 18:44 UTC, randallmorey commented on addons/api/tests/unit/models/host-catalog-test.js
> +    modelPlugin.set('compositeType', 'aws');
```suggestion

```

2022-01-14 18:44 UTC, randallmorey commented on addons/api/tests/unit/models/host-catalog-test.js
> +      type: 'static',
```suggestion
      compositeType: 'static',
```

2022-01-14 18:46 UTC, randallmorey requested changes

2022-01-14 18:46 UTC, randallmorey commented on addons/api/mirage/generated/factories/host-catalog.js
> +  plugin: function () {
```suggestion
  plugin: function (i) {
```

2022-01-14 21:42 UTC, randallmorey approved these changes

2022-01-14 21:44 UTC, merged