feat: 🎸 Add new fields to host-set model
hashicorp/boundary-ui pull request #938
Opened 2022-02-01 19:15 UTC by calcaide

Add new fields to host-set model.

2022-02-03 19:47 UTC, calcaide commented on addons/api/addon/serializers/host-set.js
> +      switch (snapshot.record.compositeType) {
A switch for just two cases might be killer, but I assume in the future we will have more cases. Happy to refactor for a simpler `if else` if you think we will not have more cases in the short-term.

2022-02-04 12:59 UTC, randallmorey requested changes

2022-02-04 12:59 UTC, randallmorey commented on addons/api/addon/serializers/host-set.js
> +  serializeStatic() {
I'd double check, but `static` probably shouldn't have `preferred_endpoints` either.

2022-02-04 12:59 UTC, randallmorey commented on addons/api/mirage/factories/host-set.js
> +    if (this.type === 'plugin' && this.plugin?.name === 'azure') {
Would a single clause `this.plugin?.name === 'azure'` be sufficient?

2022-02-06 14:05 UTC, randallmorey approved these changes

2022-02-07 16:12 UTC, merged