feat: 🎸 Combine columns on target host list for desktop
hashicorp/boundary-ui pull request #998
Opened 2022-02-24 17:23 UTC by calcaide

2022-02-24 20:53 UTC, cameronperera approved these changes

2022-02-25 16:41 UTC, randallmorey requested changes
Some minor stylistic feedback.  What if we formatted the `address` values as monospace (similar to the ID).  And what if "Dynamic" were displayed as a badge? (cc @joshuaogle)

2022-02-25 16:43 UTC, calcaide commented
> Some minor stylistic feedback. What if we formatted the `address` values as monospace (similar to the ID). And what if "Dynamic" were displayed as a badge? (cc @joshuaogle)

I like the idea of using a badge for `Dynamic` types. So the user will identify badge = types :)

Will wait for @joshuaogle feedback on it.

Thanks @randallmorey for the feedback.

2022-02-28 17:33 UTC, joshuaogle commented
I like that too, it makes sense as a badge 👍

2022-02-28 18:53 UTC, calcaide commented
@joshuaogle @randallmorey Updated PR and screenshot (after) with `Dynamic` within a badge :)

2022-02-28 19:41 UTC, randallmorey approved these changes

2022-02-28 19:51 UTC, merged